
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\py_code\pbo_uas\guiii\pembimbing_main\modul_pembimbing_dosen\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def modulpembimbingdosen():
    ModulPembimbingDosen()

#window = Tk()

#window.geometry("1005x623")
#window.configure(bg = "#313131")

class ModulPembimbingDosen(Frame):
    def __init__(self, parent, controller=None, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent
        self.configure(bg="#313131")
        self.canvas = Canvas(
            self,
            bg="#313131",
            height=700,
            width=1200,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        self.canvas.place(x=0, y=0)

        self.image_image_1 = PhotoImage(file=relative_to_assets("image_3.png"))
        image_1 = self.canvas.create_image(
            502.0,
            19.0,
            image=self.image_image_1
        )

        self.entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
        entry_bg_1 = self.canvas.create_image(
            366.5,
            465.5,
            image=self.entry_image_1
        )
        self.entry_1 = Text(
            self,
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            font=("Inter BoldItalic", 14 * -1)
        )
        self.entry_1.place(
            x=56.0,
            y=398.0,
            width=621.0,
            height=139.0
        )

        self.button_image_1 = PhotoImage(file=relative_to_assets("button_3.png"))
        button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.place(
            x=457.0,
            y=554.0,
            width=92.0,
            height=57.0
        )

        self.button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
        button_2 = Button(
            self,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            activebackground="#313131",
            relief="flat"
        )
        button_2.place(
            x=40.0,
            y=310.0,
            width=169.0,
            height=45.0
        )

        self.button_image_3 = PhotoImage(file=relative_to_assets("button_4.png"))
        button_3 = Button(
            self,
            image=self.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.parent.navigate("mng"),
            activebackground="#313131",
            relief="flat"
        )
        button_3.place(
            x=0.0,
            y=1.0,
            width=45.0,
            height=36.0
        )
        self.canvas.create_rectangle(
            40.0,
            44.0,
            966.0,
            300.0,
            fill="#D9D9D9",
            outline=""
        )

        self.image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
        image_2 = self.canvas.create_image(
            127.0,
            376.0,
            image=self.image_image_2
        )


#window.resizable(False, False)
#window.mainloop()
